source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'IFTTTLaunchImageDemo'

platform :ios, '7.0'

def install_pods
  pod "IFTTTLaunchImage", :path => "../IFTTTLaunchImage.podspec"
end

target 'IFTTTLaunchImageDemo', :exclusive => true do
  install_pods
end

target 'IFTTTLaunchImageDemoTests', :exclusive => true do
  install_pods
  pod 'FBSnapshotTestCase', '1.6'
end
